### ISSUE TITLE
What is the method of GPU acceleration for post-processing implementation?

### ISSUE THREAD

**Issue by wicyn** [cyrusbehr/YOLOv9-TensorRT-CPP#1]
I saw a document that said that, but I couldn't find it.

TODO: Need to improve postprocessing time using CUDA kernel.

**Comment by cyrusbehr** [comment]
You would modify my `tensorrt-cpp-api` project to return a GPU buffer (instead of a CPU buffer like it currently does), and then you'd implement a CUDA kernel for 1) NMS 2) bbox decoding. You're welcome to implement these and open a PR.
